# Generated by Django 4.1.7 on 2023-03-26 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='info.entries')),
                ('strength', models.PositiveSmallIntegerField()),
                ('will', models.PositiveSmallIntegerField()),
                ('influence', models.PositiveIntegerField()),
                ('observation', models.PositiveIntegerField()),
                ('lore', models.PositiveIntegerField()),
                ('loyalty', models.CharField(choices=[('Hybrid', 'Hybrid'), ('Human', 'Human')], max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='info.entries')),
                ('effect', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='info.entries')),
                ('number', models.PositiveIntegerField()),
                ('effect', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='info.entries')),
                ('effect', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ForumUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_only', models.BooleanField(verbose_name='read_only')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forumusers', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Quests',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='info.entries')),
                ('crisis', models.TextField()),
                ('target_number', models.PositiveIntegerField()),
                ('items', models.ManyToManyField(blank=True, to='info.items')),
            ],
        ),
    ]
